name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t cloud-usage-time-calculator .

      - name: Run tests against assessment image
        run: |
          docker pull mrksdh/assessment
          docker-compose up -d
          # Insert command to test application against the assessment image
